config/routes.rb
Rails.application.routes.draw do
  root to: 'application#root'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/choose_user_type', to: 'users#choose_user_type'
  post '/set_user_type', to: 'users#set_user_type'
  get '/logout', to: 'sessions#logout'
  get '/about', to: 'application#about'

  resources :users

  resources :languages, only: [:create]
  get '/languages/add_or_delete', to: 'languages#new_or_destroy', as: 'new_or_delete_language'
  post '/delete_language', to: 'languages#destroy'

  resources :users do
    resources :resources
  end

  get '/find_a_coach', to: 'users#index'
  post '/get_coach', to: 'users#get_coach'

  get '/users/:user_id/coach', to: 'users#show_coach', as: 'user_coach'
  get '/users/:user_id/student', to: 'users#show_student', as: 'user_student'


  resources :resources, only: [:index, :create, :update]
  get 'resources/top_resources', to: 'resources#top_resources', as: 'top_resources'
  get 'resources/top_resources/:id', to: 'resources#top_resource', as: 'top_resource'

  get '/auth/github/callback' => 'sessions#gh_create'
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :languages_users
  has_many :users, through: :languages_users
  has_many :resources
  has_many :subfields

  validates :name, presence: { message: 'cannot be blank.' }
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :logged_in?
  before_action :current_user, only:[:create, :destroy]


  def new_or_destroy
    @language = Language.new
  end


  def create
    if language_params[:name].empty? && language_params[:id].nil?
      redirect_to new_or_delete_language_path
    else
      if !language_params[:name].empty?
        @language = Language.find_or_create_by(name: language_params[:name])
      else
        @language = Language.find_by_id(language_params[:id])
      end

      @current_user.languages << @language if @language && !@current_user.languages.include?(@language)
      redirect_to user_path(@current_user)
    end
  end


  def destroy
    @languages = language_delete_params[:id]

    @languages.delete("")
    @languages.each do |lang_id|
      language = Language.find_by_id(lang_id)
      @current_user.languages.destroy(language)
    end

    redirect_to user_path(@current_user)
  end

  private

  def language_params
    params.require(:language).permit(:name, :id)
  end

# validates id params to accept an array of ids to be deleted at the same time 
  def language_delete_params
    params.require(:language).permit(:id => [])
  end
end

app/views/languages/new.html.erb
<div class="main">
  <h1>add a language to your profile</h1>

  <h3>choose a language from the dropdown menu, or add a new language:</h3>

  <%= form_for @language do |f| %>
    <%= f.label :id, "select a language" %>
    <%= f.collection_select :id, Language.all, :id, :name, :include_blank => true %><br><br>
    <%= f.label :name,  "or add a new language" %>
    <%= f.text_field :name %><br><br>
    <%= f.submit "add language" %>
  <% end %>
</div>

app/views/languages/new_or_destroy.html.erb
<div class="main">
  <h1>add a language to your profile</h1>

  <h3>choose a language from the dropdown menu, or add a new language:</h3>

  <% if !@language.errors.empty? %>
    <div class="error_display">
      <ul>
        <% @language.errors.full_messages.each do |error_msg| %>
          <li><%= error_msg %></li>
        <% end %>
      </ul>
    </div>

    <br>
  <% end %>

<!-- add language form -->
  <%= form_for @language do |f| %>
    <%= f.label :id, "select a language" %>
    <%= f.collection_select :id, Language.all, :id, :name, :include_blank => true %><br><br>
    <%= f.label :name,  "or add a new language" %>
    <%= f.text_field :name %><br><br>
    <%= f.submit "add language" %>
  <% end %>

<!-- delete languages form -->
  <% if !current_user.languages.empty? %>
  <br><hr>
    <h3>delete a language from your profile:</h3>

    <%= form_for @language, url: delete_language_path do |f| %>
      <%= f.label :name, "select a language" %>
      <%= f.collection_check_boxes :id, current_user.languages, :id, :name %><br><br>

      <%= f.submit "delete language" %>
    <% end %>
  <% end %>
</div>