config/routes.rb
Rails.application.routes.draw do
  root to: 'application#root'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/choose_user_type', to: 'users#choose_user_type'
  post '/set_user_type', to: 'users#set_user_type'
  get '/logout', to: 'sessions#logout'
  get '/about', to: 'application#about'

  resources :users

  resources :languages, only: [:create]
  get '/languages/add_or_delete', to: 'languages#new_or_destroy', as: 'new_or_delete_language'
  post '/delete_language', to: 'languages#destroy'

  resources :users do
    resources :resources
  end

  get '/find_a_coach', to: 'users#index'
  post '/get_coach', to: 'users#get_coach'

  get '/users/:user_id/coach', to: 'users#show_coach', as: 'user_coach'
  get '/users/:user_id/student', to: 'users#show_student', as: 'user_student'


  resources :resources, only: [:index, :create, :update]
  get 'resources/top_resources', to: 'resources#top_resources', as: 'top_resources'
  get 'resources/top_resources/:id', to: 'resources#top_resource', as: 'top_resource'

  get '/auth/github/callback' => 'sessions#gh_create'
end

app/views/resources/_form.html.erb
<% if !resource.errors.empty? %>
  <div class="error_display">
    <ul>
      <% resource.errors.full_messages.each do |error_msg| %>
        <li><%= error_msg %></li>
      <% end %>
    </ul>
  </div>

  <br>
<% end %>

<%= form_for resource do |f| %>
  <%= f.label :website, "website (i.e. StackOverflow.com, RubyOnRails.org)" %>
  <%= f.text_field :website %><br><br>

  <%= f.label :title, "resource title" %>
  <%= f.text_field :title %><br><br>

  <%= f.label :url, "link to resource"%>
  <%= f.text_field :url%><br><br>

  <%= f.label :language_id, "language" %>
  <%= f.collection_select :language_id, Language.all, :id, :name, :include_blank => true %><br><br>

  <%= f.label :subfield_id, "choose a subfield" %>
  <%= f.collection_select :subfield_id, Subfield.all, :id, :name, :include_blank => true %><br><br>

  <%= f.label :subfield_id, "or create a new subfield" %>

  <%= f.fields_for :subfield, Subfield.new do |subfields_field| %>
    <%= subfields_field.text_field :name %>
  <% end %><br><br>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.submit submit_text %>
<% end %>

app/views/resources/edit.html.erb
<div class="main">

  <h1>edit <%= @resource.title %></h1>

  <%= render partial: 'form', locals: {resource: @resource, submit_text: "update resource"} %>

</div>

app/views/resources/index.html.erb
<div class="main">

  <h1>my resources</h1>

<!-- display if user has no resources -->
  <% if @resources.empty? %>
    <p>you do not have any resources yet</p>
    <%= link_to "browse top resources", top_resources_path %><br>
    <% if current_user_is_coach? %>
      <%= link_to "add resource", new_user_resource_path(current_user) %><br>
    <% elsif current_user_is_student? %>
      <%= link_to "find a coach", find_a_coach_path %><br>
    <% end %>
  <% else %>

<!-- priority resources display -->
  <% unless @priorities.empty? %>
    <br><hr><br>
    <h2>priority</h2>
    <% @priorities.each_with_index do |resource, i| %>

      <% if @priorities.first == resource || resource.language != @priorities[i-1].language %>
        <h4><%= resource.language.name %></h4>
      <% end %>

      <li>
        <a href="#" data-resource-id="<%= resource.id %>" data-user-info="<%= user_path(current_user) %>" onClick="resourceInfo(); return false"> <%= "#{resource.subfield.name} - #{resource.website} - #{resource.title}" %> </a>

        <div style="padding-left: 30px;" id="resource-<%= resource.id %>"></div>
      </li>
    <% end %>
  <% end %>

<!-- unread resources display -->
  <% unless @unread_resources.empty? %>
    <br><hr><br>
    <h2>unread resources</h2>
    <% @unread_resources.each_with_index do |resource, i| %>

      <% if @unread_resources.first == resource || resource.language != @unread_resources[i-1].language %>
        <h4><%= resource.language.name %></h4>
      <% end %>

      <li>
        <a href="#" data-resource-id="<%= resource.id %>" data-user-info="<%= user_path(current_user) %>" onClick="resourceInfo(); return false"> <%= "#{resource.subfield.name} - #{resource.website} - #{resource.title}" %> </a>

        <div style="padding-left: 30px;" id="resource-<%= resource.id %>"></div>
      </li>
    <% end %>
  <% end %>

<!-- read resources display -->
  <% unless @read_resources.empty? %>
    <br><br><br><hr><br>
    <h2>read resources</h2>
    <% @read_resources.each_with_index do |resource, i| %>

      <% if @read_resources.first == resource || resource.language != @read_resources[i-1].language %>
        <h4><%= resource.language.name %></h4>
      <% end %>

      <li>
        <a href="#" data-resource-id="<%= resource.id %>" data-user-info="<%= user_path(current_user) %>" onClick="resourceInfo(); return false"> <%= "#{resource.subfield.name} - #{resource.website} - #{resource.title}" %> </a>
        <div style="padding-left: 30px;" id="resource-<%= resource.id %>"></div>
      </li>
    <% end %>
  <% end %>
<% end %>
</div>

<script type="text/javascript" charset="utf-8">
  function resourceInfo() {
    const protocol = window.location.protocol
    const hostUrl = window.location.host
    const userInfo = event.target.dataset.userInfo;
    const resourceId = parseInt(event.target.dataset.resourceId);
    const resourceDiv = document.getElementById("resource-" + resourceId)

    const resourcesUrl = `${protocol}//${hostUrl}${userInfo}/resources/${resourceId}`

    const liResources = $(".liResource")

    liResources.remove()

    const userResourceRoute = `${protocol}//${hostUrl}${userInfo}/resources/${resourceId}`

    fetch(userResourceRoute)
      .then( response => response.json())
      .then( json => resourceDiv.innerHTML = resourceInfo(json))

    function resourceInfo(json) {
      return `<li class="liResource"><a href=${json.url} target="_blank">visit resource on ${json.website}</a></li><li class="liResource"><a href=${resourcesUrl}>more options</a></li>`
    }
  }
</script>

app/views/resources/new.html.erb
<div class="main">

<h1>add a new resource for your student</h1>

<%= render partial: 'form', locals: {resource: @resource, submit_text: "add resource"} %>

</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    class Resource{
      constructor(website, title, url, languageId, subfieldId, userId, read, studentRating) {
        this.website = website;
        this.title = title;
        this.url = url;
        this.languageId = languageId;
        this.subfieldId = subfieldId;
        this.userId = userId;
        this.read = read;
        this.studentRating = studentRating;
      };

      websiteTitle(){ return `${this.website} - ${this.title}` };
    };

    $(function() {
      $('#new_resource').submit(function(event) {
        event.preventDefault();

        var values = $(this).serialize();
        var userId = values.charAt(values.length - 1)

        var posting = $.post('/resources', values);

        posting.done(function(data) {
          var resource = data;
          var resourcePath = `http://localhost:3000/users/` + userId + `/resources/` + resource.id;

          let newResource = new Resource(data.website, data.title, data.url, data.language_id, data.subfield_id, data.user_id, data.read, data.student_rating)

          var newestResourceDiv = document.getElementById('newestResource')
          var noResourceMessage = document.getElementById('noResourceMessage')

          newestResourceDiv.innerHTML = `<p><a href="${resourcePath}">${newResource.websiteTitle()}</a></p>`;

          noResourceMessage.innerHTML = ""
        });
      });
    });
  });
</script>

app/views/resources/show.html.erb
<div class="main">
  <h1><%= @resource.website %> - <%= @resource.title %></h1>
  <h2><%= @resource.language.name %></h2>
  <% if @resource.subfield %>
    <h2><%= @resource.subfield.name %></h2>
  <% end %>

  <br><hr><br>

  <h3><%= link_to "visit resource", @resource.url, target: :_blank  %></h3>
  <% if current_user_is_coach? %>
    <h3><%= link_to "edit resource", edit_user_resource_path(current_user, @resource) %></h3>
  <% end %>

<!-- student read, priority and ratings options -->
  <% if current_user_is_student? %>
    <br><hr><br>

    <h3>have you read this resource?</h3>
    <br>
    <%= form_for @resource, :url => resource_path(@resource), :html => {:method => :put} do |f| %>
      <p><%= f.label :read, "mark as read" %>
      <%= f.check_box :read %></p>
      <p><%= f.label :read, "mark as priority" %>
      <%= f.check_box :priority %></p>
      <p><%= f.label :student_rating, "did you find this resource helpful?" %><p>
      <p><% [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].each do |num| %>
        <%= f.label :student_rating, num %>
        <%= f.radio_button :student_rating, num %>
        <span style="color: white">|   |   |</span>
      <% end %></p><br><br>
      <%= f.submit "submit"%>
    <% end %>

  <% end %>
</div>

app/views/resources/top_resource.html.erb
<div class="main">
  <h1><%= @resource.website %> - <%= @resource.title %></h1>
  <h2><%= @resource.language.name %></h2>
  <% if @resource.subfield %>
    <h2><%= @resource.subfield.name %></h2>
  <% end %>

  <br><hr><br>

  <h3><%= link_to "visit resource", @resource.url %></h3>
</div>

app/views/resources/top_resources.html.erb
<div class="main">
  <h1>top resources</h1>
  <h4>top resources have received a student rating of 10</h4>
  <% if @top_resources.empty? %>
    <p>there are no resources with a rating of 10</p>
  <% else %>
    <div id="resources"></div>
  <% end %>
</div>

<script type="text/javascript" charset="utf-8">
  var resourcesDiv = document.getElementById("resources")

  fetch('https://code-coach-app.herokuapp.com/resources/top_resources')
    .then( response => response.json())
    .then( response => resourcesDiv.innerHTML = makeResourceLinks(response) )

  function compare(a, b) {
    if (a.title < b.title) {
      return -1
    } else if (a.title > b.title) {
      return 1
    } else {
      return 0
    }
  }

  function makeResourceLinks(resources) {
    let sortedResources = resources.sort(compare)

    let resourceLinks = sortedResources.map(function(resource){
      return `<li><a href="top_resources/${resource.id}"> ${resource.website} - ${resource.title} </a></li>`
    })

    return `<ul>${resourceLinks.join("")}</ul>`
  }
</script>