config/routes.rb
Rails.application.routes.draw do
  root to: 'application#root'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/choose_user_type', to: 'users#choose_user_type'
  post '/set_user_type', to: 'users#set_user_type'
  get '/logout', to: 'sessions#logout'
  get '/about', to: 'application#about'

  resources :users

  resources :languages, only: [:create]
  get '/languages/add_or_delete', to: 'languages#new_or_destroy', as: 'new_or_delete_language'
  post '/delete_language', to: 'languages#destroy'

  resources :users do
    resources :resources
  end

  get '/find_a_coach', to: 'users#index'
  post '/get_coach', to: 'users#get_coach'

  get '/users/:user_id/coach', to: 'users#show_coach', as: 'user_coach'
  get '/users/:user_id/student', to: 'users#show_student', as: 'user_student'


  resources :resources, only: [:index, :create, :update]
  get 'resources/top_resources', to: 'resources#top_resources', as: 'top_resources'
  get 'resources/top_resources/:id', to: 'resources#top_resource', as: 'top_resource'

  get '/auth/github/callback' => 'sessions#gh_create'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :logged_out?, only:[:root]

  private

# returns currently logged in user
  def current_user
    @current_user = User.find_by_id(session[:user_id])
  end

# returns true if current user is a coach, redirects to user home if false
  def current_user_is_coach?
    if current_user.user_type == "coach"
      true
    else
      redirect_to user_path(@current_user)
    end
  end

#returns true if current user is a student, redirects to user home if false
  def current_user_is_student?
    if current_user.user_type == "student"
      true
    else
      redirect_to user_path(@current_user)
    end
  end

# validates if profile page requested belongs to user or associated user
  def current_user_route
    if params[:id] && current_user.id == params[:id].to_i
      true
    elsif params[:id] && current_user.id != params[:id].to_i
      redirect_to user_path(@current_user)
    else
      redirect_to root_path
    end
  end

# validates if resource page requested belongs to user or associated user
  def current_user_resource
    resource = Resource.find_by_id(params[:id].to_i)
    if current_user.user_type == "student" && current_user.coach.nil?
      redirect_to user_path(@current_user)
    elsif current_user.id == resource.user_id || current_user.coach.id == resource.user_id
      true
    else
      redirect_to user_path(@current_user)
    end
  end

# validates if a user is logged_in, reroutes to root_path if not
  def logged_in?
    if session[:user_id].nil?
      redirect_to root_path
    else
      true
    end
  end

# validates if a user is logged_in, reroutes to home_page if so
  def logged_out?
    if session[:user_id]
      redirect_to user_path(current_user)
    else
      true
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def session_id
    true if session[:user_id]
  end

  def current_user
    User.find_by_id(session[:user_id])
  end

  def current_user_is_coach?
    true if current_user.user_type == "coach"
  end

  def current_user_is_student?
    true if current_user.user_type == "student"
  end
end

app/views/application/_form.html.erb
<%= form_for user do |f|%>
  <%= f.label :username %>
  <%= f.text_field :username %><br><br>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br><br>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br><br>

  <%= f.label :email %>
  <%= f.text_field :email %><br><br>

  <%= f.label :profile_img, "Profile Picture (URL)" %>
  <%= f.text_field :profile_img %><br><br>

  <%= f.label :location %>
  <%= f.text_field :location %><br><br>

  <%= f.label :github_link %>
  <%= f.text_field :github_link %><br><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br><br>

  <%= f.label :password_confirmation, "Confirm password" %>
  <%= f.password_field :password_confirmation %><br><br>

  <%= f.submit "Sign Up" %>
<% end %>

app/views/application/_nav.html.erb
<h4 id="home"><%= link_to "home", user_path(current_user) %></h4>
<h4><%= link_to "edit profile", edit_user_path(current_user) %></h4>

<!-- coach nav bar -->

<% if current_user_is_coach? %>
  <h4><%= link_to "my resources", user_resources_path(current_user) %></h4>
  <h4><%= link_to "add resource", new_user_resource_path(current_user) %></h4>
  <%if current_user_is_coach? && current_user.student %>
    <h4><%= link_to "my student", user_student_path(current_user.student) %></h4>
  <% end %>

<!-- student nav bar -->

<% elsif current_user_is_student? && current_user.coach_id.nil? %>
  <h4><%= link_to "find a coach", find_a_coach_path %></h4>
<% elsif current_user_is_student? && current_user.coach_id %>
  <h4><%= link_to "my resources", user_resources_path(current_user) %></h4>
  <h4><%= link_to "my coach", user_coach_path(current_user.coach) %></h4>
<% end %>

<h4><%= link_to "top resources", top_resources_path %></h4>
<h4><%= link_to "log out", logout_path %></h4>

app/views/application/_new_form.html.erb
<% if !user.errors.empty? %>
  <div class="error_display">
    <ul>
      <% user.errors.full_messages.each do |error_msg| %>
        <li><%= error_msg %></li>
      <% end %>
    </ul>
  </div>

  <br>
<% end %>

<%= form_for user do |f|%>
<h4>choose account type</h4>
  <div class="signup_radio">
    <p>coach</p>
    <%= f.radio_button :user_type, "coach" %><br><br>
  </div>
  <div class="signup_radio">
    <p>student</p>
    <%= f.radio_button :user_type, "student"%><br><br>
  </div>
  <br>
  <hr>
  <br>
  <%= f.label :first_name, "first name" %>
  <%= f.text_field :first_name %><br><br>

  <%= f.label :last_name, "last name" %>
  <%= f.text_field :last_name %><br><br>

  <%= f.label :username, "username" %>
  <%= f.text_field :username %><br><br>

  <%= f.label :email, "email" %>
  <%= f.text_field :email %><br><br>

  <%= f.label :profile_img, "profile picture (url)" %>
  <%= f.text_field :profile_img %><br><br>

  <%= f.label :location, "location" %>
  <%= f.text_field :location %><br><br>

  <%= f.label :github_link, "github link" %>
  <%= f.text_field :github_link %><br><br>

  <%= f.label :password, "password" %>
  <%= f.password_field :password %><br><br>

  <%= f.label :password_confirmation, "confirm password" %>
  <%= f.password_field :password_confirmation %><br><br><br>

  <%= f.submit "sign up" %><br>
<% end %>

app/views/application/_recent_resources.html.erb
<div class="recent_resources_col">
  <h3>recently added resources</h3>
  <hr>
  <% if resources.empty?%>
    <div id="newestResource"></div>
    <p id="noResourceMessage"><%= no_resources_message %></p>
  <% else %>
    <div id="newestResource"></div>
    <% resources.last(5).reverse.each do |resource| %>
    <p><%= link_to "#{resource.website} - #{resource.title}", user_resource_path(current_user, resource) %></p>
    <% end %>
    <p id="noResourceMessage"></p>
  <% end %>
</div>

app/views/application/_show_associated_profile.html.erb
<div class="main">
  <img src=<%= associated_user.profile_img %> width="125" height="125">
  <h1><%= associated_user.first_name %></h1>
  <h3><%= associated_user.username %></h3>
  <h3><%= associated_user.location.downcase %></h3>

  <% if !associated_user.github_link.empty? %>
    <h3><%= link_to "#{associated_user.first_name}'s GitHub", "http://#{associated_user.github_link}" %></h3>
  <% end %>

  <br><br><hr>

  <h3><%= associated_user.first_name %>'s programming languages</h3>
  <% if associated_user.languages.empty? %>
    <p><%= associated_user.first_name %> has not added any programming languages yet.</p>
  <% else %>
    <ul>
      <% associated_user.languages.each do |language| %>
      <li><%= language.name %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/application/_show_profile.html.erb
<div class="main">
  <img src=<%= current_user.profile_img %> width="125" height="125">
  <h1><%= current_user.username %></h1>
  <h3><%= current_user.location.downcase if current_user.location %></h3>
  <% if !current_user.github_link.empty? %>
  <h3><%= link_to "view #{current_user.first_name}'s github", current_user.github_link, target: "_blank" %></h3>
  <% end %>

  <br><br><hr>

  <h3>your programming languages</h3>
    <div id="languages" data-user-url="<%= user_path(current_user) %>"></div>
  <% if current_user.languages.empty? %>
    <p>you have not added any of your languages yet</p>
    <%= link_to "add language", new_or_delete_language_path %>
  <% else %>
    <%= link_to "add or delete languages", new_or_delete_language_path %>
  <% end %>
</div>


<script type="text/javascript" charset="utf-8">
  var protocol = window.location.protocol
  var hostUrl = window.location.host
  var languagesDiv = document.getElementById("languages");
  var userUrl = languagesDiv.dataset.userUrl;
  var currentUserRoute = `${protocol}//${hostUrl}${userUrl}`

  fetch(currentUserRoute)
    .then( response => response.json())
    .then( response => languagesDiv.innerHTML = listOfLanguages(response.languages) )

  function listOfLanguages(languages) {
    const languagesList = languages.map(language => `<li>${language.name}</li>`)
    return `<ul>${languagesList.join("")}</ul>`
  }
</script>



<!-- <script type="application/json" src="languages.js"></script> -->

app/views/application/about.html.erb
<% if session_id %>
  <div class="main">
<% else %>
  <div class="access_section" >
<% end %>
  <h1>about</h1>
  <hr>
  <p id="about">CodeCoach was founded with one simple principle in mind: that every child should have the opportunity to learn and build valuable, hard-skills to take through life.</p>

  <p id="about">We provide a platform for seasoned software developers to pair with students who are interested in learning to code, but don't know where to begin or have the resources to find out. The developers, or coaches, who are familiar with the world of software engineering are able to work directly with his or her student to understand what the student is interested in learning, and then build out a library of all open-source materials to act as the core of the student's custom curriculum.</p>
  
  <p id="about">The resources are out there, but knowing where to start can be an insurmountable barrier for some. We hope that CodeCoach will help our community to bring that barrier down for the next generation.</p>
</div>

app/views/application/index.html.erb
<div class="access_section" id="enter_site">
  <h1><%= link_to "sign up", new_user_path %></h1>

  <hr>

  <h1><%= link_to "log in", login_path %></h1>
<div>

app/views/application/mentor_login.html.erb
<h2>Mentor login</h2>

<%= form_for @mentor do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br><br>

  <%= f.label :password %>
  <%= f.text_field :password %><br><br>

  <%= f.submit "Log In" %>
<% end %>

app/views/application/root.html.erb
<div class="access_section" id="enter_site">
  <h1><%= link_to "sign up", new_user_path %></h1>

  <hr>

  <h1><%= link_to "log in", login_path %></h1>
<div>

app/views/application/student_login.html.erb
<h2>Student login</h2>

<%= form_for @student do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br><br>

  <%= f.label :password %>
  <%= f.text_field :password %><br><br>

  <%= f.submit "Log In" %>
<% end %>