config/routes.rb
Rails.application.routes.draw do
  root to: 'application#root'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/choose_user_type', to: 'users#choose_user_type'
  post '/set_user_type', to: 'users#set_user_type'
  get '/logout', to: 'sessions#logout'
  get '/about', to: 'application#about'

  resources :users

  resources :languages, only: [:create]
  get '/languages/add_or_delete', to: 'languages#new_or_destroy', as: 'new_or_delete_language'
  post '/delete_language', to: 'languages#destroy'

  resources :users do
    resources :resources
  end

  get '/find_a_coach', to: 'users#index'
  post '/get_coach', to: 'users#get_coach'

  get '/users/:user_id/coach', to: 'users#show_coach', as: 'user_coach'
  get '/users/:user_id/student', to: 'users#show_student', as: 'user_student'


  resources :resources, only: [:index, :create, :update]
  get 'resources/top_resources', to: 'resources#top_resources', as: 'top_resources'
  get 'resources/top_resources/:id', to: 'resources#top_resource', as: 'top_resource'

  get '/auth/github/callback' => 'sessions#gh_create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>code coach</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Raleway:200,400');
      @import url('https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700');
    </style>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="google-signin-client_id" content="ENV['GOOGLE_CLIENT_ID'].apps.googleusercontent.com">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
  </head>

  <body>

<!-- codecoach header -->

    <header>
      <div id="logo"><a href="/""><span style="color: white; padding-left: 20px">code</span><span style="color: rgb(204, 217, 229); font-weight: bold;">coach</span></a></div>
    </header>

<!-- navigation bar if user is logged in -->

    <% if session_id && current_user.user_type %>
      <nav>
        <%= render partial: 'application/nav' %>
      </nav>
    <% end %>

<!-- individual page renders -->

    <%= yield %>

<!-- recent resources section if user is logged in with custom no resource messages -->

    <% if session_id && current_user_is_coach? %>
      <%= render partial: 'application/recent_resources', locals: {resources: current_user.resources, no_resources_message: "you have not added any resources yet"} %>

    <% elsif session_id && current_user_is_student? && current_user.coach %>
      <%= render partial: 'application/recent_resources', locals: {resources: current_user.coach.resources, no_resources_message: "you do not have any resources yet" } %>

      <% elsif session_id && current_user_is_student? && current_user.coach.nil? %>
        <%= render partial: 'application/recent_resources', locals: {resources: [], no_resources_message: "you do not have any resources yet" } %>
    <% end %>

<!-- footer section for logged in and logged out user -->

    <footer>
      <h6><%= mail_to "bryn.bennett@gmail.com", "contact"%></h6>
      <h6><%= link_to "about", about_path %></h6>
      <% if session_id %>
        <h6><%= link_to "my profile", user_path(current_user) %> </h6>
        <h6><%= link_to "log out", logout_path %></h6>
      <% else %>
        <h6><%= link_to "log in", login_path %> </h6>
        <h6><%= link_to "sign up", new_user_path %></h6>
      <% end %>
    </footer>

  </body>
</html>

<!-- <script type="application/javascript" src="languages.js"></script> -->